Quality of life improvements
thomas-ashcraft/alienware_arena_helper pull request #13
Opened 2019-09-16 11:46 UTC by Lucki

This adds some quality of life improvements to the daily quests.

Some can be done automatically:
* Swap badge
* Swap border
* Share content
* Visit news

Some can be improved to solve manually:
* Swap avatar -> quick link to personalization site (currently untested/placeholder since the quest is quite rare)
* Post replies -> quick link to the AWA On-Topic forum section
* Visit page -> quick link to the AWA On-Topic forum section

___

I haven't done something with JavaScript before so let me know when there's something to improve.

P.S.: I have no idea what changed in the first line, I copied the old line in this and git still tells me there has something changed.

2019-09-17 11:42 UTC, thomas-ashcraft commented
> P.S.: I have no idea what changed in the first line, I copied the old line in this and git still tells me there has something changed.

Most likely this is UTF BOM. Shouldn't really affect functionality in our case. Can be a problem only when you creating something that working with files in straight ways.

2019-09-17 12:33 UTC, thomas-ashcraft commented
This is awesome! Automatic daily quests resolving - this is what I dreamt to make. You made that dream come true. Thank you!

Not immediately able to find a button to solve the quest. I think we need to make it a little more noticeable when the quest is not yet complete.

Script messages aren't visible with opened sidebar because script UI is lies under it.

But those notes relates to script UI design for the new site interface is whole dedicated task that I can find a time for.

2019-09-17 12:34 UTC, thomas-ashcraft approved these changes

2019-09-17 12:37 UTC, thomas-ashcraft requested changes

2019-09-17 12:37 UTC, thomas-ashcraft commented on alienwarearena_helper.user.js
> +						<span class="more-link right"></span></a>`).appendTo(".col-2");
```.col-2``` can be a common selector. There is better to make something like ```.quest-item > .col-2```

2019-09-17 13:14 UTC, merged

2019-09-17 13:22 UTC, Lucki commented
Thanks!

2019-10-02 04:31 UTC, thomas-ashcraft commented
Have made a little improvement to set previous avatar border back in automatic way.

Looking forward to make the same for badges.